```{r}
library(lubridate)
library(rmarkdown)
library(knitr)
library(ggplot2)
library(GGally)
library(class)
library(Hmisc)
library(corrplot)
library(class)
library(randomForest)
library(mda)
library(klaR)
library(car)
```

```{r}
#loading dataset. Dataset need to be in the same folder of the project.
load_dataset = function(data_folder, file){
  PATH = paste(getwd(), data_folder, file, sep="/")
}


##the normalization function is created
nor = function(x) { (x -min(x))/(max(x)-min(x))   }


##this function divides the correct predictions by total number of predictions that tell us how accurate teh model is.
accuracy = function(x){sum(diag(x)/(sum(rowSums(x)))) * 100}
precision = function(x){(diag(x)/((rowSums(x)))) * 100}
recall = function(x){(diag(x)/((colSums(x)))) * 100}


sample_sub <- function(data, perc){
  
  num = nrow(data) * as.numeric(perc)
  ran = sample(1:num, 0.95 * num)

  a_s = data[ran,]
  diff = setdiff(data,a_s)
  
  ran_test = sample(1:nrow(diff), 0.05 * num)
  a_t = diff[ran_test,]

  return(list(a_s, a_t))
}


#returns two dataset: train and test
get_balanced_dataset = function(data, balanced_gender=0, hard_balance = F){
  
  if (balanced_gender == 0){
    
    #Balance only wrt AGE GROUPS
    a = subset(data, age_groups == 1)
    b = subset(data, age_groups == 2)
    c = subset(data, age_groups == 3)
    d = subset(data, age_groups == 4)

    ran = sample(1:nrow(d), 0.95 * nrow(d))
    
    a_s = a[ran,]
    b_s = b[ran,]
    c_s = c[ran,]
    d_s = d[ran,]
    
    a = setdiff(a,a_s)
    b = setdiff(b,b_s)
    c = setdiff(c,c_s)
    d = setdiff(d,d_s)
    
    ran_test = sample(1:nrow(d), 1 * nrow(d))
    
    a_t = a[ran_test,]
    b_t = b[ran_test,]
    c_t = c[ran_test,]
    d_t = d[ran_test,]
  
    data_train = rbind(a_s, b_s, c_s, d_s)
    data_test = rbind(a_t, b_t, c_t, d_t)
    
    rm(a,b,c,d, a_s, b_s, c_s, a_t, b_t, c_t)
    
    return(list(data_train, data_test))
  
  }else{
    
    if(hard_balance == T){
      #Balance GENDER & AGE GROUPS
      f = subset(data, gender == 2)
      m = subset(data, gender == 1)
      
      gend = list(f,m)
      
      full_train = vector(mode='list', length=2)
      full_test = vector(mode='list', length=2) 
      
      
      for (i in (1:length(gend))){
        
        if (i == 1){
          perc = list(0.05, 0.1, 0.3, 1)
        }else{
          perc = list(0.02, 0.02, 0.1, 0.4)
        }
        
        a = subset(as.data.frame(gend[[i]]), (age_groups == 1))
        full_a = sample_sub(a, perc[1])
        
        b = subset(as.data.frame(gend[[i]]), (age_groups == 2))
        full_b = sample_sub(b, perc[2])
        
        c = subset(as.data.frame(gend[[i]]), (age_groups == 3))
        full_c = sample_sub(c, perc[3])
        
        d = subset(as.data.frame(gend[[i]]), (age_groups == 4))
        full_d = sample_sub(d, perc[4])
        
        data_train = rbind(full_a[[1]], full_b[[1]], full_c[[1]], full_d[[1]])
        data_test = rbind(full_a[[2]], full_b[[2]], full_c[[2]], full_d[[2]])
      
        full_train[[i]] = data_train
        full_test[[i]] = data_test
        
      }   
      
      data_train = as.data.frame(rbind(full_train[[1]], full_train[[2]]))
      data_test = as.data.frame(rbind(full_test[[1]], full_test[[2]]))

      rm(full_a, full_b, full_c, full_d, full_train, full_test)
      
      return(list(data_train, data_test))    
      
    }else{
          m = subset(data, gender == 1)
          f = subset(data, gender == 2)
          
          ran = sample(1:nrow(f), 0.95 * nrow(f))
          m_s = m[ran,]
          f_s = f[ran,]
          
          m = setdiff(m,m_s)
          f = setdiff(f,f_s)
          
          ran_test = sample(1:nrow(f), 1 * nrow(f))
          
          f_t = f[ran_test,]
          m_t = m[ran_test,]
        
          data_train = rbind(f_s, m_s)
          data_test = rbind(f_t, m_t)
          
          rm(f,m,f_s, m_s, f_t, m_t)
          return(list(data_train, data_test))
    }
  }
}

table_gender_age <- function(train, test){
  cat("TAB TRAIN")
  print(table(train$gender, train$age_groups))
  
  cat("\n", "TAB TEST")
  print(table(test$gender, test$age_groups))
}



# ++++++++++++++++++++++++++++
# flattenCorrMatrix
# ++++++++++++++++++++++++++++
# cormat : matrix of the correlation coefficients
# pmat : matrix of the correlation p-values
flattenCorrMatrix <- function(cormat, pmat) {
  ut <- upper.tri(cormat)
  data.frame(
    row = rownames(cormat)[row(cormat)[ut]],
    column = rownames(cormat)[col(cormat)[ut]],
    cor  =(cormat)[ut],
    p = pmat[ut]
    )
}


rstudio_viewer <- function(file_name, file_path = NULL) {
    temporary_file <- tempfile()
    dir.create(temporary_file)
    html_file <- file.path(temporary_file, file_name)
    current_path <- ifelse(is.null(file_path),
                           getwd(),
                           path.expand(file_path))
    file.copy(file.path(current_path, file_name), html_file)
    rstudioapi::viewer(html_file)
}

plot_stats <- function(tab, mode="test", cf=F){
  
  cat("\n", "---------", mode, "---------", "\n")
  
  cat("\nAccuracy: ", round(accuracy(tab),2))
  cat("\nPrecision: ", round(precision(tab),2))
  cat("\nRecall: ", round(recall(tab),2), "\n")
  
  if(cf == T){
      cat("\n", "---------", "CF", "---------", "\n")
      tab
  }

}


our_palette = c(rgb(1, 0, 0), 
              rgb(0, 1, 0), 
              rgb(0, 0, 1), 
              rgb(1, 0.5, 0))

```

```{r}
tripdata_2020_r = read.csv(load_dataset("SL_dataset", "tripdata_2020_r.csv"))
tripdata_2020_r = tripdata_2020_r[sample(1:nrow(tripdata_2020_r)),]

```

```{r}
cat("min age:", min(tripdata_2020_r$age))
cat("\nmax age:", max(tripdata_2020_r$age))
cat("\nusers >85y:", nrow(tripdata_2020_r[tripdata_2020_r$age > 85,]))
cat("\nusers <=85:", nrow(tripdata_2020_r[tripdata_2020_r$age <= 85 & tripdata_2020_r$age > 0,]))
```

```{r}
par(mfrow=c(1,2))

hist(tripdata_2020_r$age[tripdata_2020_r$age != 0], 
     breaks = 20,
     xlab = "Age",
     main = "Age Histogram 2019")


dens = density(tripdata_2020_r$age[tripdata_2020_r$age != 0])
plot(dens,main = "Age density 2019")
```


```{r}
split_ages = c(16, 30, 45, 65, 85)

data_u85_20 = tripdata_2020_r[tripdata_2020_r$age <= 85 & tripdata_2020_r$age > 0,]
data_u85_20$age_groups = cut(data_u85_20$age, breaks=split_ages, include.lowest = TRUE, labels = FALSE)

data_o85_20 = tripdata_2020_r[tripdata_2020_r$age > 85 | tripdata_2020_r$age == 0,]
data_o85_20$age_groups = cut(data_o85_20$age, breaks=split_ages, include.lowest = TRUE, labels = FALSE)

data_u85_20 = subset(data_u85_20, select = -c(age, birth.year, year, start.station.name, end.station.name))
data_o85_20 = subset(data_o85_20, select = -c(age, age_groups, birth.year, year, start.station.name, end.station.name))

data_u85_20$tripduration = round(data_u85_20$tripduration/60,2)
data_u85_20$starttime = round(data_u85_20$starttime/60,2)
data_u85_20$stoptime = round(data_u85_20$stoptime/60,2)

data_u85_20[c("starttime", "stoptime")] = lapply(data_u85_20[c("starttime", "stoptime")], nor)

data_o85_20$tripduration = round(data_o85_20$tripduration/60,2)
data_o85_20$starttime = round(data_o85_20$starttime/60,2)
data_o85_20$stoptime = round(data_o85_20$stoptime/60,2)

data_o85_20[c("starttime", "stoptime")] = lapply(data_o85_20[c("starttime", "stoptime")], nor)

```

```{r}
barplot_age_group = barplot(table(data_u85_20$age_groups), 
     main = "Age groups count",
     xlab = "Age group",
     ylab = "Freq",
     col = "light Blue")
```

```{r}
par(mfrow=c(1,2))

t=table(tripdata_2020_r$usertype, tripdata_2020_r$month)
s=colSums(t)
for (i in 1:12){
  t[2*i-1] = t[2*i-1]/s[i]
  t[2*i] = t[2*i]/s[i]
}
barplot(t,
        main='Usertype fraction per month',
        xlab='Month',
        ylab='Fraction',
        col=our_palette[3:4],
        legend=TRUE,
        args.legend = list(legend=(c('Subscriber', 'Customer'))))


```
```{r}
EDA_UT = subset(tripdata_2020_r, select = c(tripduration, usertype))

customer_dur = EDA_UT[EDA_UT$usertype == 0,]
subscriber_dur = EDA_UT[EDA_UT$usertype == 1,]

den_customer = density(log(customer_dur$tripduration))
den_subscriber = density(log(subscriber_dur$tripduration))

plot(den_customer, main="Customer vs Sub trip duration", col=our_palette[3])
lines(den_subscriber, col=our_palette[3])

abline(v=mean(log(customer_dur$tripduration)),
       col = our_palette[3],
       lwd =3)
abline(v=mean(log(subscriber_dur$tripduration)),
       col = our_palette[4],
       lwd =3)

legend("topright", 
       legend = c("Customer", "Subscriber"),
       fill = c(our_palette[3], our_palette[4]))
 

# Fill the areas
polygon(den_customer, col = rgb(0, 0, 1, alpha = 0.6))
polygon(den_subscriber, col = rgb(1, 0.5, 0, alpha = 0.6))

x = seq(4, 12, by = .1)
y = dnorm(x, mean = mean(log(customer_dur$tripduration)), sd = sd(log(customer_dur$tripduration)))
lines(x,y, type='l',
      lwd=3,
      col = our_palette[3])

x = seq(4, 12, by = .1)
y = dnorm(x, mean = mean(log(subscriber_dur$tripduration)), sd = sd(log(subscriber_dur$tripduration)))
lines(x,y, type='l',
      lwd=3,
      col = our_palette[4])
```

```{r}
par(mfrow=c(1,2))

qqPlot(log(customer_dur$tripduration),
       ylab='Customer trip duration',
       envelope=TRUE)
qqPlot(log(subscriber_dur$tripduration),
       ylab='Subscriber trip duration',
       envelope=TRUE)

```
```{r}
EDA_gender = subset(tripdata_2020_r, select = c(tripduration, gender))

male_dur = EDA_gender[EDA_gender$gender == 1,]
female_dur = EDA_gender[EDA_gender$gender == 2,]

den_male = density(log(male_dur$tripduration))
den_female = density(log(female_dur$tripduration))

plot(den_male, main="Gender trip duration", col=our_palette[2])
lines(den_female, col=our_palette[1])

abline(v=mean(log(male_dur$tripduration)),
       col = our_palette[2],
       lwd =3)
abline(v=mean(log(female_dur$tripduration)),
       col = our_palette[1],
       lwd =3)

legend("topright", 
       legend = c("Male", "Female"),
       fill = c(our_palette[2], our_palette[1]))


# Fill the areas
polygon(den_male, col = rgb(0, 1, 0, alpha = 0.2))
polygon(den_female, col = rgb(1, 0, 0, alpha = 0.2))

x = seq(4, 12, by = .1)
y = dnorm(x, mean = mean(log(male_dur$tripduration)), sd = sd(log(male_dur$tripduration)))
lines(x,y, type='l',
      lwd=3,
      col = our_palette[2])

x = seq(4, 12, by = .1)
y = dnorm(x, mean = mean(log(female_dur$tripduration)), sd = sd(log(female_dur$tripduration)))
lines(x,y, type='l',
      lwd=3,
      col = our_palette[1])
```
c(rgb(1, 0, 0), 
              rgb(0, 1, 0),
```{r}
par(mfrow=c(1,1))

qqPlot(log(male_dur$tripduration),
       ylab='Customer trip duration',
       envelope=TRUE)
qqPlot(log(female_dur$tripduration),
       ylab='Subscriber trip duration',
       envelope=TRUE)
```

```{r}
tab = table(tripdata_2019_r$gender, tripdata_2019_r$usertype)
hist = barplot(tab, 
        beside = TRUE, 
        legend = FALSE,
        main = "Gender and UserType",
        xlab = "UserType",
        ylab = "Freq",
        ylim=c(0, max(tab) + 100000),
        names.arg = c("Customer: 0", "Subscriber: 1"),
        col = heat.colors(3))

legend("topleft", legend = c("Unknown", "Male", "Female"),
       fill = heat.colors(3))

text(x = hist, y = tab + 50000, labels = tab, cex = .8)


```



```{r}
den_trip_p = density(log(data_o85_20$tripduration[data_o85_20$age_groups==4]), adjust = 3.5)
den_trip_19 = density(log(data_u85$tripduration[data_u85$age_groups==4]), adjust = 3.5)


plot(den_trip_19,xlim = c(0,8), main = "trip density over age 4", col = our_palette[1], lwd = 2)
lines(den_trip_p, col = our_palette[2], lwd = 2)
```

```{r}
tripdata_2019_r = read.csv(load_dataset("SL_dataset", "tripdata_2019_r.csv"))
```


```{r}
######### JOIN 2020 ###############

data_u85_20_19 = tripdata_2019_r[tripdata_2019_r$age <= 85,]
data_u85_20_19$age_groups = cut(data_u85_20_19$age, breaks=split_ages, include.lowest = TRUE, labels = FALSE)

data_u85_20_19 = subset(data_u85_20_19, select = -c(age, birth.year, year, start.station.name, end.station.name))

data_u85_20_19$tripduration = round(data_u85_20_19$tripduration/60,2)
data_u85_20_19$starttime = round(data_u85_20_19$starttime/60,2)
data_u85_20_19$stoptime = round(data_u85_20_19$stoptime/60,2)

data_u85_20_19[c("tripduration", "starttime", "stoptime")] = lapply(data_u85_20_19[c("tripduration", "starttime", "stoptime")], nor)

data_u85_20_19 = data_u85_20_19 %>% drop_na()


#table(data_u85_20_20$gender, data_u85_20_20$age_groups)


data_u85_20 = rbind(data_u85_20, data_u85_20_19)
data_u85_20 = subset(data_u85_20, select = -c(gender))
data_o85_20 = subset(data_o85_20, select = -c(gender))
```

```{r}
data_u85_20 = rbind(data_u85_20, data_u85)
```


#Let's try to predict the 0-age  and >80 age
```{r}
################# == 0 ################
full = get_balanced_dataset(data_u85_20, balanced_gender = 0)
data_train = data_u85_20[1:300000,]
data_test = data_u85_20[300000:415849,]

labels_train = data_train$age_groups
labels_test = data_test$age_groups

data_train = subset(data_train, select = -c(age_groups))
data_test = subset(data_test, select = -c(age_groups))

rf_model = randomForest(x = data_train,
                             y = as.factor(labels_train),
                             ntree = 100)


rf_model_pred_train = predict(rf_model, newdata = data_train)
rf_model_pred = predict(rf_model, newdata = data_test)

# train resuls
tab_train_rf = table(rf_model_pred_train, labels_train)
plot_stats(tab_train_rf, mode="train", cf = T)
  
# test result
tab_test_rf = table(rf_model_pred, labels_test)
plot_stats(tab_test_rf, mode="test", cf = T)


# Variable importance plot
varImpPlot(rf_model)
```

```{r}
data_o85_20 = subset(data_o85_20, selct = -c(stratday, stopday))
data_u85_20 = subset(data_u85_20, selct = -c(stratday, stopday, age_groups))

pred_o = predict(rf_model, newdata = subset(data_o85_20, select = -c(gender)))

new = data_u85_20[data_u85_20$gender != 0,]
label_new = new$gender
new = subset(new, select = -c(gender))

pred_u = predict(rf_model, newdata = new)

table(pred_o)

plot_stats(table(label_new, pred_u), cf = T)

#data_o85_20$age_groups = dec_age

#data_age = rbind(data_u85_20, data_o85_20)
```
```{r}
barplot(table(dec_age))
barplot(table(data_u85$age_groups))
```
```{r}
#FARE DI NUOVO DOPO LE PREDIZIONI
c1 = density(data_u85_20[data_u85_20$age_groups == 1,]$month, adjust = 7)
c2 = density(data_u85_20[data_u85_20$age_groups == 2,]$month, adjust = 7)
c3 = density(data_u85_20[data_u85_20$age_groups == 3,]$month, adjust = 7)
c4 = density(data_u85_20[data_u85_20$age_groups == 4,]$month, adjust = 3.5)

plot(c1, xlim = c(1,12), main = "Age density over months", col = our_palette[1], lwd = 2)
lines(c2, col = our_palette[2], lwd = 2)
lines(c3, col = our_palette[3], lwd = 2)
lines(c4, col = our_palette[4], lwd = 2)


legend("topright", 
       legend = c("Group 1: 16-30", "Group 2: 31-45", "Group 3: 46-65", "Group 4: 65+"),
       fill = our_palette)
```

```{r}
data_u85_20 = subset(data_u85_20, select = -c(startday, stopday, bikeid))

rf_100_g = readRDS('rf_best.rda')
rf_50_g = readRDS('rf_best_g_50.rda')
rf_100_g = readRDS('rf_best_g_10.rda')


pred_1 = predict(rf_100, newdata = subset(data_u85_20, select = -c(age_groups)))
pred_2 = predict(rf_50, newdata = subset(data_u85_20, select = -c(age_groups)))
pred_3 = predict(rf_10, newdata = subset(data_u85_20, select = -c(age_groups)))

a = as.data.frame(pred_1)
colnames(a) = c("pred_a")
a$pred_a = as.numeric(a$pred_a)

b = as.data.frame(pred_2)
colnames(b) = c("pred_b")
b$pred_b = as.numeric(b$pred_b)

c = as.data.frame(pred_3)
colnames(c) = c("pred_c")
c$pred_c = as.numeric(c$pred_c)

a$pred_b = (b$pred_b)
a$pred_c = (c$pred_c)
a$pred_a = (a$pred_a)
rm(b,c)

pred_1a = (a$pred_a)
pred_2a = (a$pred_b)
pred_3a = (a$pred_c)
df_prob_1 = as.data.frame(predict(rf_100, newdata=subset(data_u85_20, select = -c(age_groups)), type='prob'))
df_prob_2 = as.data.frame(predict(rf_50, newdata=subset(data_u85_20, select = -c(age_groups)), type='prob'))
df_prob_3 = as.data.frame(predict(rf_10, newdata=subset(data_u85_20, select = -c(age_groups)), type='prob'))

final = vector(mode="list", length = length(pred_1a))
w_class = c(0.48, 0.72, 0.79, 0.98)
c = 0

ty <- function(num, pred){

  if(length(num) != 1){
    return(pred)
  }else{
    return(num)
  }
}

for (i in (1:length(final))){
  if(pred_1a[i] == pred_2a[i] | pred_1a[i] == pred_3a[i] | pred_3a[i] == pred_2a[i]){
    final[i] = pred_1a[i]
  }else{
    prob_pred_1 = df_prob_1[i,]
    prob_pred_2 = df_prob_2[i,]
    prob_pred_3 = df_prob_3[i,]

    m1 = max(prob_pred_1)
    m2 = max(prob_pred_2)
    m3 = max(prob_pred_3)

    pos1 = which(prob_pred_1 == m1)
    pos2 = which(prob_pred_2 == m2)
    pos3 = which(prob_pred_3 == m3)
    
    pos1 = ty(pos1, pred_1a[i])
    pos2 = ty(pos2, pred_2a[i])
    pos3 = ty(pos3, pred_3a[i])

    val1 = 0.50 * (as.numeric(w_class[pos1]) * m1)
    val2 = 0.30 * (as.numeric(w_class[pos2]) * m2)
    val3 = 0.20 * (as.numeric(w_class[pos3]) * m3)
    
    fin = max(val1, val2, val3)
    if(fin == val1){
      pos = pos1
    }

    if(fin == val2){
      pos = pos2
    }
    
    if(fin == val3){
      pos = pos3
    }
    final[i] = 1
    c = c+1
  }
}
a$fin = as.numeric(final)

# test result
res = table(a$fin, data_u85_20$age_groups)
plot_stats(res, cf = T)
```

#GENDER ASSUMER 2020

```{r}
data_no_gender = data_age[data_age$gender == 0]
data_gender = data_age[data_age$gender != 0]

y_gender = predict(rf_model, newdata = pred_dataset[,-10])

table(y_gender)

data_f = rbind(data_gender, data_no_gender)
```

```{r}
data = subset(tripdata_2020_r, select = c(age_groups,
                                          start.station.name,
                                          start.station.latitude, 
                                          start.station.longitude,
                                          end.station.name,
                                          end.station.latitude, 
                                          end.station.longitude))

EDA_id_station = subset(data, select = c(start.station.name,
                                         end.station.name,
                                         age_groups))

# TOP 10 START #
tab = as.data.frame(table(EDA_id_station$start.station.name))
top_10_start = tab[order(tab$Freq, decreasing = T),][1:10,]
colnames(top_10_start) = c("start_name", "Freq")

start_tab = data.frame(matrix(NA, nrow = nrow(top_10_start), ncol = 4))
colnames(start_tab) = c("1","2", "3", "4")

for (rowIdx in 1:(nrow(start_tab))) {
  for (colIdx in 1:(ncol(start_tab))) {
    start_tab[rowIdx, colIdx] = nrow(subset(EDA_id_station, age_groups == colIdx & start.station.name == top_10_start[rowIdx,1]))
  }
}

start_tab$start_name = top_10_start$start_name



# TOP 10 END #
end_tab = as.data.frame(table(EDA_id_station$end.station.name))
top_10_end = tab[order(end_tab$Freq, decreasing = T),][1:10,]
colnames(top_10_end) = c("end_name", "Freq")

end_tab = data.frame(matrix(NA, nrow = nrow(top_10_end), ncol = 4))
colnames(end_tab) = c("1","2", "3", "4")

for (rowIdx in 1:(nrow(end_tab))) {
  for (colIdx in 1:(ncol(end_tab))) {
    end_tab[rowIdx, colIdx] = nrow(subset(EDA_id_station, age_groups == colIdx & end.station.name == top_10_end[rowIdx,1]))
  }
}

end_tab$end_name = top_10_end$end_name

```


```{r}
bar = barplot(as.matrix(subset(start_tab, select = -c(start_name))), 
        beside = T,
        cex.names = 1,
        horiz = T,
        las=1,
        main = "TOP-10 Most used start station by age",
        space = c(0,3),
        col = heat.colors(nrow(start_tab)))

legend("topright", legend = start_tab$start_name,
       fill = heat.colors(nrow(start_tab)), cex = 0.8)


bar = barplot(as.matrix(subset(end_tab, select = -c(end_name))), 
        beside = T,
        cex.names = 1,
        horiz = T,
        las=1,
        main = "TOP-10 Most used end station by age",
        space = c(0,3),
        col = heat.colors(nrow(start_tab)))

legend("topright", legend = end_tab$end_name,
       fill = heat.colors(nrow(end_tab)), cex = 0.8)

```


```{r}
tab = as.data.frame(table(data$age_groups, data$start.station.name, data$start.station.latitude))
temp = order(colSums(tab), decreasing = T) #da errore 
temp = as.data.frame(tab[,temp[1:10],])

par(mar=c(4,16,4,0))
barplot(temp,
        beside=TRUE,
        col = c("darkgrey", "darkblue", "red", "yellow"),
        las=1,
        cex.axis = 1,
        horiz = TRUE
        )
```


```{r}
temp$start.station.name[1]
```

```{r}
map_start = subset(sub_data, select = c(start.station.name,
                                  start.station.latitude, 
                                  start.station.longitude))
map_start = map_start[!duplicated(map_start[ , c("start.station.name")]),]
map_start = map_start[map_start$start.station.name %in% start_tab$start_name,]


map_end = subset(sub_data, select = c(end.station.name,
                                  end.station.latitude, 
                                  end.station.longitude))
map_end = map_end[!duplicated(map_end[ , c("end.station.name")]),]
map_end = map_end[map_end$end.station.name %in% end_tab$end_name,]



pos_20 = cbind(map_start, 
               end.station.name = map_end$end.station.name,
               end.station.latitude = map_end$end.station.latitude,
               end.station.longitude = map_end$end.station.longitude)

write.csv(pos_20, paste(getwd(), "SL_dataset/2020_pos.csv", sep = "/"), row.names = FALSE)
```


```{python}
import pandas as pd
import numpy as np
import folium
import webbrowser

df_acc = pd.read_csv('C:/Users/39345/Desktop/SL_project/SL_dataset/2020_pos.csv', dtype=object)

map_hooray = folium.Map(location=[42.361145, -71.057083], zoom_start = 12) 

df_acc['start.station.name'] = df_acc['start.station.name'].astype(str)
df_acc['start.station.latitude'] = df_acc['start.station.latitude'].astype(float)
df_acc['start.station.longitude'] = df_acc['start.station.longitude'].astype(float)


feature_group = folium.FeatureGroup("LocationsStart")
lat = df_acc['start.station.latitude']
lng = df_acc['start.station.longitude']
name = df_acc['start.station.name']

for lt, lg, nm in zip(lat, lng, name):
    feature_group.add_child(folium.Marker(location=[lt,lg],popup=nm,icon=folium.Icon(color="blue")))

map_hooray.add_child(feature_group)

map_hooray.save("BostonMap_2020.html")
```


```{r}
tab = as.data.frame(table(data$age_groups, data$start.station.name))
colnames(tab) = c("age_groups", "start.station.name", "freq")


for (idx in 1:length(split_ages)){
  if (idx == 1){
    one = tab[tab$age_groups == 1,]
    temp = one[order(one$freq, decreasing = T),][1:10,]
  }
  
  other = tab[tab$age_groups == idx,]
  temp = rbind(temp, (other[order(other$freq, decreasing = T),][1:10,]))
}


temp$lat = NA
temp$long = NA

for (idx in 1:nrow(temp)){
  name = temp$start.station.name[idx]
  
  temp[idx, 4] = data$start.station.latitude[data$start.station.name == name][1]
  temp[idx, 5] = data$start.station.longitude[data$start.station.name == name][1]
}


write.csv(temp, paste(getwd(), "SL_dataset/start_station_by_age_20.csv", sep = "/"), row.names = FALSE)
```



```{python}
df_acc = pd.read_csv('C:/Users/39345/Desktop/SL_project/SL_dataset/start_station_by_age_20.csv', dtype=object)

df_acc['start.station.name'] = df_acc['start.station.name'].astype(str)
df_acc['age_groups'] = df_acc['age_groups'].astype(int)
df_acc['freq'] = df_acc['freq'].astype(int)
df_acc['lat'] = df_acc['lat'].astype(float)
df_acc['long'] = df_acc['long'].astype(float)


for i in range(1, 8):
  map_hooray = folium.Map(location=[42.361145, -71.057083], zoom_start = 12) 
  feature = "LocationsStart_" + str(i)
  
  
  fil = df_acc[df_acc['age_groups'] == i]
  feature_group = folium.FeatureGroup(feature)
  lat = fil['lat']
  lng = fil['long']
  name = fil['start.station.name']
  
  
  for lt, lg, nm in zip(lat, lng, name):
      feature_group.add_child(folium.Marker(location=[lt,lg],popup=nm,icon=folium.Icon(color="blue")))
  
  
  map_hooray.add_child(feature_group)
  map_hooray.save("BostonMap_age_2020_" + str(i) + ".html")

```

```{r}
rstudio_viewer("BostonMap_age1.html", getwd())
```
